### ISSUE TITLE
部署成功，但无法连接自己的notion表格

### ISSUE THREAD

**Issue by asiyoua** [hyoban/kodoku#2]
按照步骤部署完成，但是点击notion template还是kodoku的订阅。
notion表格已连接集成，token填写了集成的，id写了表格网址的数字部分。
表格是公开的，已经publish。

实在想不出来哪一步错了……
前来求教！
![image](https://github.com/hyoban/kodoku/assets/48462903/f7acc0e8-f042-48a4-8bfd-23fa401c5e62)

**Comment by hyoban** [comment]
页面中订阅的内容是你自己的数据库就说明成功了，首页的那个 notion template 就是固定的。

**Comment by asiyoua** [comment]
感谢回复。在自己的数据库更新条目以后，多久会刷新显示成新的内容呢？
还是说，最开始订阅的内容不会被删除，只是会出现新增内容？
看您在论坛里写的是两小时刷新一次，是说：在我修改条目之后，需要等待两个小时才能同步成功吗？

**Comment by aloasut** [comment]
redploy就可以马上出来

**Comment by hyoban** [comment]
> 感谢回复。在自己的数据库更新条目以后，多久会刷新显示成新的内容呢？ 还是说，最开始订阅的内容不会被删除，只是会出现新增内容？ 看您在论坛里写的是两小时刷新一次，是说：在我修改条目之后，需要等待两个小时才能同步成功吗？

这是可以配置的，每个路由下的 `page.tsx` 中可以设置。

https://github.com/hyoban/kodoku/blob/main/app/subscription/page.tsx#LL10C31-L10C31

同样地，你可以手动 redeploy 来立刻看到更新

**Comment by asiyoua** [comment]
> redploy就可以马上出来

感谢！

**Comment by asiyoua** [comment]
> > 感谢回复。在自己的数据库更新条目以后，多久会刷新显示成新的内容呢？ 还是说，最开始订阅的内容不会被删除，只是会出现新增内容？ 看您在论坛里写的是两小时刷新一次，是说：在我修改条目之后，需要等待两个小时才能同步成功吗？
> 
> 这是可以配置的，每个路由下的 `page.tsx` 中可以设置。
> 
> https://github.com/hyoban/kodoku/blob/main/app/subscription/page.tsx#LL10C31-L10C31
> 
> 同样地，你可以手动 redeploy 来立刻看到更新

好嘞，我之后试试看，感谢～
