### ISSUE TITLE
notion条目里有哪些是必填的？

### ISSUE THREAD

**Issue by asiyoua** [hyoban/kodoku#3]
根据上一条修改好表格内容以后，发现deploy失败。又发现v2ex上有人和我同样的问题：
![image](https://github.com/hyoban/kodoku/assets/48462903/1e1effcf-55ec-4f42-8389-9329c142bd4e)

我试着把自己添加的条目删掉，deploy成功了。

已知：**我加了两个条目，添加了RSS链接和homepage这两个字段的内容。**
猜测：需要按照某种格式填写内容。
**问题：不知道哪些条目是必填的，可以让我deploy成功的？**

**Comment by hyoban** [comment]
https://github.com/hyoban/kodoku/blob/main/lib/notion.ts#L68-L76

**Comment by Loongphy** [comment]
可以看下日志，可能是新建的没有设置封面（cover）
![image](https://github.com/hyoban/kodoku/assets/42089082/005ae7ba-3743-47f4-9dff-f045198705ae)

**Comment by asiyoua** [comment]
> https://github.com/hyoban/kodoku/blob/main/lib/notion.ts#L68-L76

收到~

**Comment by asiyoua** [comment]
> 可以看下日志，可能是新建的没有设置封面（cover） ![image](https://user-images.githubusercontent.com/42089082/242445006-005ae7ba-3743-47f4-9dff-f045198705ae.png)

果然，是没传封面。万万没想到封面是必填项！
感谢~
